---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-from-manifest
  namespace: default
spec:
  encryptedData:
    password: AgAgILWmcJybigQZGEsuonraOOcJMqneu6fSSqVWn4CCEddRrGOEw2AMxGpnqG4zOgZr9ZT683AJOlaTHZPUKxShxucUTy/r9bUhMI9D4gWuCzkd0dQvdA+BkxQhczCYiaY4cJR8QC+1fUM54WjaUUsDSw9HXU/DRiWf//QcTZBMhEn/u3Qe+jrU3DuhI5USpKRP8DmtCqRU8+S2fdMJ8O5O/YpMnvvZFuJBtN+Un7ccuSpb3MJtYPcI8EsintmPXIRUfpQRJFqorbX12n9zYIVbOzBORKjabICK6V4cwRs4MzAgRiBCkETdldycLdKQnoyjJJWIiMDu0wJbwcDqoHxnUnCecokUuxX0sQ56gY1rnk6q8VXnSdl4/QT1jEtSDptRqp24pt2bnSdo7AUefVbPNNoCip2v8tj/txvpSOyygcIVPrtmY19cAyGhjr5F/J55NenoHANWftpejpaba0j8Fm7Kgu6Bn/18W67KUxjpbKfFKc6HS7wEsasAN3o/ldTvapJXujOMleTrttiII7QdSl2LE/fqbIaTOBJB4xYGVpCzVehKAROiTGEsybAaRorL63nFebXz5d8Vfl3YOAjICS0voTJ3gINxLZD/mGnnRsrIP/6mEjgbMiB8AcqHNlXn2GDWO4D6cSCGJbYnLHI1TxAVTEexuY16/aGHBS8EDhTTy1SbvrfoW6pb2C1NNWGwG9p7XmVGZ3VOfmk8GQmWwnOorg==
    user: AgAC/icLXaF9HSaYz8i5n7SsI60Eo8zBBVLxGtPWY5NKhnFdAH5HIZ0zvujsDDs4Iwk5l5XtOtbt5eiY4sUfl3pUW5Sy5tAPV+/8I+SjJ7/yq0d2QH4JUd/d+xSYi2tNMHjUHflEjVRFM7UEvs4P3HAn+Q4fufnpQ9MuuDrVia3fYEYeiEMICvgdT3Ws61OmoOCC3SnALT4ATge9wrkCNeI2tsBJgoEyMDZF/xKdJmdix6DZEEqy4DP7VPkjfD3wwVRK+OcOZAjBgjoY8Qx19/aUZnsxxWdqux5vluj7MxtFlnr+a7D5DTEwiixvP7/upt/Nk44hFBQgfGHdCs13FQUtilR1Xk37ZhZWq6hGMAVaqBb+x1sZU5S9eOg37AQgDyizKZIDbBiR12KA6P1sEZCrhBxTvAMxdThB2RQMYQmHFlz/6mWz+ck8JOAL9Szyu4YqWiOxdKEWOHJqgpY+plGzAphjspi4EZvF+ZuhV6r2GM0CnnKNfex5GM4vTwIqM5ZJotyic2bVAaU8l18GvDRIoORHlXYrebm87xdm54VosFDpprikmR9bQV+cZ1tRiiFgABcEat80Bn6QHkrINyGvxJZyDW+BdWdxMnD5sCn5eb/TXsLIJ5FgKNYU2fPfC5BWykOnQITHkVuZgTWV+J4YblSe8GXg4z4M/aaiUEN5liA9g7x/Dq/LDIpC3dP89Ay2zid/bs5/dS5HH398ldiVh1HljQ==
  template:
    metadata:
      creationTimestamp: null
      name: secret-from-manifest
      namespace: default
    type: Opaque
